export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_PROPERTYLIST = 'FETCH_PROPERTYLIST';
export const FETCH_PROPERTYLIST_SUCCESS = 'FETCH_PROPERTYLIST_SUCCESS';
export const FETCH_PROPERTYLIST_FAILURE = 'FETCH_PROPERTYLIST_FAILURE';

export const FETCH_USER_PROPERTIES = 'FETCH_USER_PROPERTIES';

export const FETCH_PROPERTY = 'FETCH_PROPERTY';
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';
export const FETCH_PROPERTY_FAILURE = 'FETCH_PROPERTY_FAILURE';

export const EMAIL_CONFIRM = 'EMAIL_CONFIRM';
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS';
export const EMAIL_CONFIRM_FAILURE = 'EMAIL_CONFIRM_FAILURE';

export const POST_PROPERTY = 'POST_PROPERTY';
export const SEARCH_PROPERTY = 'SEARCH_PROPERTY';
