export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const FETCH_PROPERTY = 'FETCH_PROPERTY';
export const FETCH_PROPERTYLIST = 'FETCH_PROPERTYLIST';
export const FETCH_PROPERTY_DETAILS = 'FETCH_PROPERTY_DETAILS';
export const FETCH_USER_PROPERTIES = 'FETCH_USER_PROPERTIES';
export const POST_PROPERTY = 'POST_PROPERTY';
export const SEARCH_PROPERTY = 'SEARCH_PROPERTY';
export const DELETE_PROPERTY_DETAILS = 'DELETE_PROPERTY_DETAILS';

